version: "3.8"

services:
  api:
    build: ./node_express_app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: compose_test

  mysql:
    build: ./mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
