/**
 * ⚙️ PM2 Cluster Mode: /generate-report Example
 *
 * This version is designed to be run via PM2 in cluster mode.
 * No manual cluster setup is needed—PM2 handles worker creation and load balancing.
 *
 * ✅ Use PM2 to run it across all CPU cores:
 *    pm2 start pm2_generate_report.js -i max
 *
 * 📌 -i max automatically forks one worker per core.
 */

const express = require("express");
const os = require("os");
const process = require("process");

const app = express();
const PORT = process.env.PORT || 3000;
const pid = process.pid;
const cpuCount = os.cpus().length;

console.log(`🔧 Worker PID: ${pid} | CPUs available: ${cpuCount}`);

app.get("/generate-report", (req, res) => {
  console.log(`📄 [/generate-report] Handled by PID ${pid}`);
  let total = 0;

  // Simulate intensive computation
  for (let i = 0; i < 1e5; i++) {
    for (let j = 0; j < 1e4; j++) {
      total += Math.sin(i) * Math.tan(j) * 0.0000001;
    }
  }

  res.send(`📄 Report generated by PID ${pid}: ${total.toFixed(2)}`);
});

app.listen(PORT, () => {
  console.log(`🚀 Server listening at http://localhost:${PORT} (PID: ${pid})`);
});
